[task]
nonce = "Ft8BCnVqqGIAAAAAhW+GaLdBA4NZcjq+"
commit = "df6cc0ec563fd50e6e9fd6f1d6b9d1a315fc5402"
time = 1979-05-27T07:32:00Z
content = "./content"

[task.run]
before = """
"""
script = """
"""
after = """
"""
