[task]
nonce = "Ft8BCnVqqGIAAAAAhW+GaLdBA4NZcjq+"
commit = "df6cc0ec563fd50e6e9fd6f1d6b9d1a315fc5402"
time = 1979-05-27T07:32:00Z
content = "./content"

[task.run]
before = """
ra.result = exec cat ${ra.content.path}
"""

script = """
new_file_path = replace ${ra.content.path} .txt .new.txt
new_file_content = replace ${ra.result.stdout} This That
writefile ${new_file_path} ${new_file_content}
ra.result = exec cat ${new_file_path}
"""

after = """
ra.result = exec cat ${new_file_path}
"""
